apiVersion: operator.aquasec.com/v1alpha1
kind: AquaScanner
metadata:
  name: aqua
spec:
  infra:                                    
    serviceAccount: "aqua-sa"               
    version: "4.6"                          
  deploy:                                   
    replicas: 1                             
  login:                                    
    username: "scanner"
    password: "<Password>"
    host: "http://aqua-server:8080"
