# permissions for end users to view aquadatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquadatabase-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases/status
  verbs:
  - get
