# permissions for end users to edit aquacsps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquacsp-editor-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquacsps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquacsps/status
  verbs:
  - get
