# permissions for end users to edit aquaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquaserver-editor-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers/status
  verbs:
  - get
