# permissions for end users to view aqualightnings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aqualightning-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aqualightnings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aqualightnings/status
  verbs:
  - get
