# permissions for end users to edit aquadatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquadatabase-editor-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquadatabases/status
  verbs:
  - get
