# permissions for end users to view aquaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquaserver-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaservers/status
  verbs:
  - get
