# permissions for end users to view aquagateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquagateway-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways/status
  verbs:
  - get
