# permissions for end users to edit aquagateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquagateway-editor-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquagateways/status
  verbs:
  - get
