# permissions for end users to view aquakubeenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquakubeenforcer-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers/status
  verbs:
  - get
