# permissions for end users to edit aquastarboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquastarboard-editor-role
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - aquastarboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aquasecurity.github.io
  resources:
  - aquastarboards/status
  verbs:
  - get
