# permissions for end users to view aquaenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquaenforcer-viewer-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquaenforcers/status
  verbs:
  - get
