# permissions for end users to edit aquakubeenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquakubeenforcer-editor-role
rules:
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.aquasec.com
  resources:
  - aquakubeenforcers/status
  verbs:
  - get
