# permissions for end users to view aquastarboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquastarboard-viewer-role
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - aquastarboards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aquasecurity.github.io
  resources:
  - aquastarboards/status
  verbs:
  - get
