apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aqua-operator
  template:
    metadata:
      labels:
        name: aqua-operator
    spec:
      serviceAccountName: aqua-operator
      containers:
        - name: aqua-operator
          image: "aquasec/aqua-operator:1.0.2"
          command:
          - aqua-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aqua-operator"
