kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-operator
subjects:
- kind: ServiceAccount
  name: aqua-operator
  # namespace: aqua # optional
roleRef:
  kind: Role
  name: aqua-operator
  apiGroup: rbac.authorization.k8s.io
