## Append samples you want in your CSV to this file as resources ##
resources:
- operator_v1alpha1_aquacsp.yaml
- operator_v1alpha1_aquadatabase.yaml
- operator_v1alpha1_aquaenforcer.yaml
- operator_v1alpha1_aquagateway.yaml
- operator_v1alpha1_aquakubeenforcer.yaml
- operator_v1alpha1_aqualightning.yaml
- operator_v1alpha1_aquascanner.yaml
- operator_v1alpha1_aquaserver.yaml
- aquasecurity_v1alpha1_aquastarboard.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
